name: PlatformIO Test and Release

on:
  push:
    branches:
      - IoT

jobs:
  test:
    name: Run PlatformIO tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/IoT
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Install PlatformIO
        run: |
          pip install platformio
      
      - name: Build and test with PlatformIO
        run: |
          platformio test --environment native
          
  create_firmware_image:
    name: Create firmware image
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ${{ github.workspace }}/IoT 
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Install PlatformIO
        run: |
          pip install platformio
      
      - name: Create firmware image
        run: |
          platformio run --environment target_run

      - name: Upload firmware image
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: IoT/.pio/build/target_run/firmware.hex
          
      - name: Upload test env
        uses: actions/upload-artifact@v2
        with:
          name: test-env
          path: |
            IoT/lib/
            IoT/test/
            IoT/platformio.ini
