apiVersion: v1
kind: Service
metadata:
  name: sep4-smart-pot1-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: sep4-smart-pot1
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: sep4-smart-pot1
  sessionAffinity: None
