name: Cloud CI/CD Pipeline

on: 
  workflow_dispatch: 
  push:
    paths:
      - 'Cloud/**'
    branches:
      - Cloud  # Triggers on a push to the 'Cloud' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'

      - name: Authenticate gcloud CLI
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./Cloud
          file: ./Cloud/Dockerfile
          push: true
          tags: europe-north1-docker.pkg.dev/graphical-tape-419210/cloud-app-repo/smart-pot-cloud-container:latest

      - name: Check if instance exists
        id: check_instance
        run: |
          if gcloud compute instances describe my-cloud-instance --zone=europe-north1-a --format="value(name)"; then
            echo "INSTANCE_EXISTS=true" >> $GITHUB_ENV
          else
            echo "INSTANCE_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Update Instance Tags and Metadata
        if: env.INSTANCE_EXISTS == 'true'
        run: |
          gcloud compute instances add-tags my-cloud-instance --zone=europe-north1-a --tags=http-server
          gcloud compute instances add-metadata my-cloud-instance --zone=europe-north1-a --metadata=google-logging-enabled=true,google-monitoring-enabled=true,ASPNETCORE_ENVIRONMENT=Development

      - name: Update Instance Container Image
        if: env.INSTANCE_EXISTS == 'true'
        run: |
          gcloud beta compute instances update-container my-cloud-instance \
            --zone europe-north1-a \
            --container-image europe-north1-docker.pkg.dev/graphical-tape-419210/cloud-app-repo/smart-pot-cloud-container:latest \
            --container-arg="--publish=80:80" \
            --container-arg="--publish=11000:11000"
      
      
      - name: Create Compute Engine Instance
        if: env.INSTANCE_EXISTS == 'false'
        run: |
          gcloud compute instances create-with-container my-cloud-instance \
            --container-image europe-north1-docker.pkg.dev/graphical-tape-419210/cloud-app-repo/smart-pot-cloud-container:latest \
            --zone europe-north1-a \
            --machine-type e2-micro \
            --tags=http-server \
            --metadata=google-logging-enabled=true,google-monitoring-enabled=true,ASPNETCORE_ENVIRONMENT=Development \
            --container-port=80 \
            --container-port=11000
