name: Cloud CI/CD Pipeline

on:
  push:
    paths:
      - 'Cloud/**'
    branches:
      - Cloud  # This triggers on a push to the 'Cloud' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'  # Specify your .NET Core version here

      - name: Build with dotnet
        run: dotnet build Cloud/Cloud.csproj --configuration Release  # Specify the project file explicitly

      - name: Dotnet Test
        run: dotnet test Cloud/Cloud.csproj --no-restore --verbosity normal  # Specify the project file explicitly

      - name: Login to Google Cloud
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/cloud-app:${{ github.sha }} Cloud/

      - name: Push Docker Image to GCR
        run: |
          gcloud auth configure-docker
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/cloud-app:${{ github.sha }}

      - name: Deploy to Google Cloud Compute Engine
        run: |
          gcloud compute instances create-with-container my-cloud-instance \
            --container-image gcr.io/${{ secrets.GCP_PROJECT_ID }}/cloud-app:${{ github.sha }} \
            --zone us-central1-a \
            --machine-type e2-medium
