name: Cloud CI/CD Pipeline

on:
  push:
    paths:
      - 'Cloud/**'
    branches:
      - Cloud  # Triggers on a push to the 'Cloud' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Set a timeout for the job to avoid infinite hangs

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log Project ID and Image Tag (Masked)
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          PROJECT_ID_MASKED="${GCP_PROJECT_ID:0:4}****${GCP_PROJECT_ID: -4}"
          echo "Project ID (masked): $PROJECT_ID_MASKED"
          echo "Image (masked): europe-north1-docker.pkg.dev/$PROJECT_ID_MASKED/cloud-app-repo:${{ github.sha }}"

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'  # Specify your .NET Core version here

      - name: Build and Test Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./Cloud
          file: ./Cloud/Dockerfile
          push: false
          tags: europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-app-repo:${{ github.sha }}
          load: true  # Load the built image into Docker daemon to test it afterwards

      - name: Test Application
        if: steps.check_image.outputs.image_exists == 'true'
        run: |
          docker run --name test-app europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-app-repo:${{ github.sha }} &
          sleep 10  # Wait for the application to start
          docker logs test-app
          docker stop test-app

      - name: Authenticate gcloud CLI
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: "gcloud"

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev --quiet

      - name: Check if Image Exists in Artifact Registry
        id: check_image
        run: |
          EXISTS=$(gcloud artifacts docker images list europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-app-repo --filter="tags:${{ github.sha }}" --format="get(tags)")
          if [[ "$EXISTS" == *"${{ github.sha }}"* ]]; then
            echo "Image exists."
            echo "::set-output name=image_exists::true"
          else
            echo "Image does not exist."
            echo "::set-output name=image_exists::false"
          fi

      - name: Push Docker Image to GCR
        if: steps.check_image.outputs.image_exists == 'false'
        run: |
          docker push europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-app-repo:${{ github.sha }}

      - name: Deploy to Google Cloud Compute Engine
        if: steps.check_image.outputs.image_exists == 'false'
        run: |
          gcloud compute instances create-with-container my-cloud-instance \
            --container-image europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-app-repo:${{ github.sha }} \
            --zone europe-north1-a \
            --machine-type e2-medium

      - name: Health Check
        run: |
          echo "Checking if the application is healthy..."
          sleep 30  # Wait a bit for the application to settle
          status_code=$(curl -o /dev/null -s -w "%{http_code}\n" https://34.88.7.34/)
          if [ "$status_code" -ne 200 ]; then
            echo "Health check failed!"
            exit 1
          fi
          echo "Health check passed!"
